"""Languages in different datasets- with cv LC naming"""

CV_LANGUAGES: list[str] = [
    "ab",
    "af",
    "am",
    "ar",
    "as",
    "ast",
    "az",
    "ba",
    "bas",
    "be",
    "bg",
    "bn",
    "br",
    "ca",
    "ckb",
    "cnh",
    "cs",
    "cv",
    "cy",
    "da",
    "de",
    "dv",
    "dyu",
    "el",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gl",
    "gn",
    "ha",
    "he",
    "hi",
    "hsb",
    "ht",
    "hu",
    "hy-AM",
    "ia",
    "id",
    "ig",
    "is",
    "it",
    "ja",
    "ka",
    "kab",
    "kk",
    "kmr",
    "ko",
    "ky",
    "lg",
    "lij",
    "lo",
    "lt",
    "ltg",
    "lv",
    "mdf",
    "mhr",
    "mk",
    "ml",
    "mn",
    "mr",
    "mrj",
    "mt",
    "myv",
    "nan-tw",
    "ne-NP",
    "nhi",
    "nl",
    "nn-NO",
    "nso",
    "oc",
    "or",
    "os",
    "pa-IN",
    "pl",
    "ps",
    "pt",
    "quy",
    "rm-sursilv",
    "rm-vallader",
    "ro",
    "ru",
    "rw",
    "sah",
    "sat",
    "sc",
    "sk",
    "skr",
    "sl",
    "sq",
    "sr",
    "sv-SE",
    "sw",
    "ta",
    "te",
    "th",
    "ti",
    "tig",
    "tk",
    "tok",
    "tr",
    "tt",
    "tw",
    "ug",
    "uk",
    "ur",
    "uz",
    "vi",
    "vot",
    "yi",
    "yo",
    "yue",
    "zgh",
    "zh-CN",
    "zh-HK",
    "zh-TW",
    "zu",
    "zza",
]

# Updated on April 2024 from https://github.com/openai/whisper/blob/main/whisper/tokenizer.py
WHISPER_LANGUAGES: list[str] = [
    "af",
    "am",
    "ar",
    "as",
    "az",
    "ba",
    "be",
    "bg",
    "bn",
    "bo",
    "br",
    "bs",
    "ca",
    "cs",
    "cy",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fo",
    "fr",
    "gl",
    "gu-IN", # gujarati "gu" in Whisper
    "ha",
    "haw", # Hawaiian - NOT IN CV
    "he",
    "hi",
    "hr",
    "ht",
    "hu",
    "hy-AM", # armenian "hy" in Whisper
    "id",
    "is",
    "it",
    "ja",
    "jv", # javanese "jw" in Whisper
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "la", # latin - NOT IN CV
    "lb",
    "ln",
    "lo",
    "lt",
    "lv",
    "mg",
    "mi", # maori - NOT IN CV
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "my", # Myanmar - Burmese in CV
    "ne-NP", # nepali "ne" in Whisper
    "nl",
    "nn-NO", # nynorsk "nn" in Whisper
    "no", # norwegian => nb-NO ? (Norwegian Bokmål) in CV? (not yet released)
    "oc",
    "pa-IN", # punjabi "pa" in Whisper
    "pl",
    "ps",
    "pt",
    "ro",
    "ru",
    "sa", # sanskrit - NOT IN CV
    "sd",
    "si",
    "sk",
    "sl",
    "sn", # shona - NOT IN CV
    "so",
    "sq",
    "sr",
    "su", # sundanese - NOT IN CV
    "sv-SE", # swedish "sv" in Whisper
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tk",
    "tl",
    "tr",
    "tt",
    "uk",
    "ur",
    "uz",
    "vi",
    "yi",
    "yo",
    "yue",
    "zh-CN", # chinese "zh" in Whisper
]

FLEURS_LANGUAGES: list[str] = [
    "ar",
    "as",
    "ast",
    "az",
    "be",
    "bg",
    "bn",
    "ca",
    "ckb",
    "cs",
    "cy",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "fa",
    "fi",
    "fr",
    "ga-IE",
    "gl",
    "ha",
    "hi",
    "hu",
    "hy-AM",
    "id",
    "ig",
    "is",
    "it",
    "ja",
    "ka",
    "kk",
    "ko",
    "ky",
    "lg",
    "lo",
    "lt",
    "lv",
    "mk",
    "ml",
    "mn",
    "mr",
    "mt",
    "ne-NP",
    "nl",
    "oc",
    "or",
    "pa-IN",
    "pl",
    "pt",
    "ro",
    "ru",
    "sk",
    "sl",
    "sr",
    "sv-SE",
    "sw",
    "ta",
    "th",
    "tr",
    "uk",
    "ur",
    "uz",
    "vi",
    "yo",
    "yue",
]

VOXPOPULI_LANGUAGES: list[str] = [
    "cs",
    "de",
    "en",
    "es",
    "et",
    "fi",
    "fr",
    "hu",
    "it",
    "lt",
    "nl",
    "pl",
    "ro",
    "sk",
    "sl",
]

# LANGUAGES WITH EXTERNAL TEST SET
LANGUAGES_ALLOWED: list[str] = sorted(list(set(VOXPOPULI_LANGUAGES + FLEURS_LANGUAGES)))

#
# CV - WHISPER language codes: Unmatched ones
#
# 'bo', # Tibetan - IN PROGRESS
# 'bs', # Bosnian - IN PROGRESS
# 'fo', # faroese - IN PROGRESS
# 'gu', # gujarati => gu-IN - IN PROGRESS
# 'haw', # hawaiian - NOT IN CV
# 'hr', # croatian - IN PROGRESS
# 'hy', # armenian => hy-AM
# 'jw', # javanese => jv
# 'km', # Khmer - IN PROGRESS
# 'kn', # kannada - IN PROGRESS
# 'la', # latin - NOT IN CV
# 'lb', # luxembourgish - IN PROGRESS
# 'ln', # lingala - IN PROGRESS
# 'mg', # malagasy - IN PROGRESS
# 'mi', # maori - NOT IN CV
# 'ms', # malay - IN PROGRESS
# 'my', # Myanmar - Burmese in CV
# 'ne', # nepali => ne-NP
# 'nn', # nynorsk => nn-NO (Norwegian Nynorsk)
# 'no', # norwegian => nb-NO (Norwegian Bokmål ???)
# 'pa', # punjabi => pa-IN
# 'sa', # sanskrit - NOT IN CV
# 'sd', # sindhi - IN PROGRESS
# 'si', # sinhala - IN PROGRESS
# 'sn', # shona - NOT IN CV
# 'so', # somali - IN PROGRESS
# 'su', # sundanese - NOT IN CV
# 'sv', # swedish => sv-SE
# 'tg', # tajik - IN PROGRESS
# 'tl', # tagalog - IN PROGRESS
# 'zh' # chinese => zh-CN
